version: "3.7"

services:
    floods:
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes: # use volumes for hot reloading
            - ./src:/app/src
        expose:
            - '227'
        ports:
            - '227:227'
        command: npm run dev
        environment:
            NODE_ENV: development
            APP_ENV: local
            MONGO_URI: mongodb://root:password@mongodb:27017/floods?authSource=admin&readPreference=primary&ssl=false

    mongodb:
        image: mongo
        command: --logpath /dev/null
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data_container:/data/db
          
volumes:
    mongodb_data_container:
          